Update modele

diff --git a/scripts/change_url b/scripts/change_url
--- a/scripts/change_url
+++ b/scripts/change_url
@@ -36,6 +36,10 @@ test -n "$new_path" || new_path="/"
 new_path=$(ynh_normalize_url_path $new_path)
 old_path=$(ynh_normalize_url_path $old_path)
 
+echo "old_path=$old_path" >&2	## DEBUG
+echo "new_path=$new_path" >&2	## DEBUG
+echo "-" >&2	## DEBUG
+
 #=================================================
 # CHECK WHICH PARTS SHOULD BE CHANGED
 #=================================================
@@ -53,18 +57,11 @@ then
 fi
 
 #=================================================
-# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
+# MANAGE FAILURE OF THE SCRIPT
 #=================================================
 
-if [ $change_domain -eq 0 ]
-then
-	# The backup process will failed if the domain has changed, because the file settings.yml has already changed
-	BACKUP_BEFORE_UPGRADE	# Backup the current version of the app
-	ynh_clean_setup () {
-		BACKUP_FAIL_UPGRADE	# restore it if the upgrade fails
-	}
-	ynh_abort_if_errors	# Active trap pour arrêter le script si une erreur est détectée.
-fi
+# Exit if an error occurs during the execution of the script
+ynh_abort_if_errors
 
 #=================================================
 # STANDARD MODIFICATIONS
@@ -77,14 +74,39 @@ nginx_conf_path=/etc/nginx/conf.d/$old_domain.d/$app.conf
 # Change the path in the nginx config file
 if [ $change_path -eq 1 ]
 then
+	# Make a backup of the original nginx config file if modified
+	ynh_backup_if_checksum_is_different "$nginx_conf_path"
+
+	# Replace locations starting with old_path
+	# Look for every location possible patterns (see https://nginx.org/en/docs/http/ngx_http_core_module.html#location)
+	ynh_replace_string "location\( \(=\|~\|~\*\|\^~\)\)\? $old_path" "location\1 $new_path"  "$nginx_conf_path"
+	# Replace path in "return" directives
+	ynh_replace_string "return \([[:digit:]]\{3\}\) $old_path" "return \1 $new_path"  "$nginx_conf_path"
+
 	ynh_replace_string "location $old_path" "location $new_path" "$nginx_conf_path"
+
+	# Calculate and store the nginx config file checksum
+	ynh_store_file_checksum "$nginx_conf_path"
 fi
 
 # Change the domain for nginx
 if [ $change_domain -eq 1 ]
 then
-	sudo mv $nginx_conf_path /etc/nginx/conf.d/$new_domain.d/$app.conf
+	# Delete file checksum for the old conf file location
+	ynh_delete_file_checksum "$nginx_conf_path"
+	mv $nginx_conf_path /etc/nginx/conf.d/$new_domain.d/$app.conf
+
+	nginx_conf_path=/etc/nginx/conf.d/$new_domain.d/$app.conf
+	# Calculate and store the nginx config file checksum
+	ynh_store_file_checksum "$nginx_conf_path"
 fi
+
+#=================================================
+# UPDATE SSOWAT
+#=================================================
+
+sudo cat "/etc/yunohost/apps/$app/settings.yml" >&2	## DEBUG
+echo "-" >&2	## DEBUG
 
 #=================================================
 # SPECIFIC MODIFICATIONS
@@ -98,4 +120,6 @@ fi
 # RELOAD NGINX
 #=================================================
 
-sudo systemctl reload nginx
+cat "$nginx_conf_path" >&2	## DEBUG
+
+systemctl reload nginx
